---
- name: Verify
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: test connection
      ansible.builtin.ping:

    - name: Example assertion
      ansible.builtin.assert:
        that: true
